import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";
import {IoIosArrowForward} from "react-icons/io"
import Navbar from './component/Navbar';
import Home from './component/Home';
import About from './component/About';
import ChooseUs from './component/ChooseUs';
import Testimonial from './component/Testimonial';
import Contact from './component/Contact';
import Footer from './component/Footer';
import CopyWrite from './component/CopyWrite';

export default function Index() {
  return (
    <>
      <Head>
        <title>Avalon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-[url('/images/top_bg.png')] bg-no-repeat bg-cover min-h-screen max-h-full py-5 ">
          <Navbar/>
          <Home/>
        </section>
        <About/>
        <ChooseUs/>
        <Testimonial/>
        <Contact/>
      </main>
      <footer>
        <Footer/>
        <CopyWrite/>
      </footer>
    </>
  )
}
